### PR TITLE
fix: Race condition when playing/pausing audio

### LINKED ISSUE #1687: Race condition when playing/pausing audio
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

When `AudioPlayer.pause()` is called a short time after `AudioPlayers.play()` is called, the pause will not take effect. The sound file will play in its entirety.

Same goes for `AudioPlayer.stop()` instead of `.pause()`.

### Expected behaviour

When `pause()` is the latest call to an `AudioPlayer`, the audio doesn't play.

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. Play any sound from the _Sources_ tab. You'd expect the audio won't play since it's paused 5 milliseconds after being played. But in fact, it plays to completion.

### Code sample

<details>
<summary>Code sample</summary>

Go to the official example's [`lib/tabs/sources.dart` file](https://github.com/bluefireteam/audioplayers/blob/main/packages/audioplayers/example/lib/tabs/sources.dart#L64-L71) and replace the `_play()` method with the following:

```dart
  Future<void> _play(Source source) async {
    await player.stop();
    Timer(const Duration(milliseconds: 5), () {
      // Imagine this is a handler to some event that 
      // happens independently.
      player.pause();
    });
    await player.play(source);
    toast(
      'Set and playing source.',
      textKey: const Key('toast-set-play'),
    );
  }
```

</details>

### Affected platforms

Android, iOS, web, Windows, Linux, macOS

### Platform details

_No response_

### AudioPlayers Version

main, 5.2.0

### Build mode

debug

### Audio Files/URLs/Sources

_No response_

### Screenshots

_No response_

### Logs

_No response_

### Related issues / more information

Note that everything works as expected if you do something like:

```dart
await player.play(source);
await player.pause();
```

But in an app or game, events come from different sources. For example, settings can be updated (read from file) on startup, at almost the exact same moment as music is started. This can lead to the following:

1. Game starts
2. Game asks for settings (async)
3. Music starts (because that's the default) --- `play(...)`
4. Settings are finished reading from something like `shared_preferences`, and they say "no audio"
5. Music is immediately asked to stop --- `stop()`
6. Music continues to play indefinitely because the `stop()` finishes before the `play()` can get to the `resume()` step

FWIW, I couldn't replicate the behavior when using `resume()` (i.e. the source is already loaded). So I think the problem stems from the steps included in the `play()` method, which is not atomic.

Related Discord discussion: https://discord.com/channels/509714518008528896/533299043686940692/1168866344742162463

### Working on PR

no way

### PR DESCRIPTION
**Pull request by Gustl22**
# Description

Fixes #1687

Instead we could also set the state always at the beginning of each method, but this raises these problems:
- If the operation in the method throws an error, the state doesn't match the native players state
- The state doesn't reflect the current real world audio state, as it's maybe still preparing/buffering and not actually playing

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `refactor:`,
      `docs:`, `chore:`, `test:`, `ci:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation and added dartdoc comments with `///`, where necessary.
- [x] I have updated/added relevant examples in [example].

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

#1687

[issue database]: https://github.com/bluefireteam/audioplayers/issues
[Contributor Guide]: https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#feature-requests--prs
[Conventional Commit]: https://conventionalcommits.org
[example]: https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example

### CODE REVIEW

**Review by spydon — COMMENTED** [review]
Why do the methods need to be split up into a private and a public method? 🤔

File: packages/audioplayers/lib/src/audioplayer.dart [hunk 1]
```diff
@@ -205,7 +218,7 @@ class AudioPlayer {
       await seek(position);
     }
 
-    await resume();
+    await _resume();
```
Comment (Gustl22) [inline packages/audioplayers/lib/src/audioplayer.dart:221]: @spydon to not override the public player state with `resume` method, we need to call the `_resume` only. Since the other methods are used only once, except `_resume`, I can revert the change to not get as confusing.

**Review by spydon — APPROVED** [review]
