### PR TITLE
fix: Improve Error handling for Unsupported Sources

### LINKED ISSUE #748: bug(iOS): crash with space is in source url
when i try to play audio i get this error and that cause crashing application:

```
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file audioplayers/SwiftAudioplayersPlugin.swift, line 518
```

### LINKED ISSUE #972: Non-ASCII characters in sound file names doesn't work on iOS
Hi and thanks for an awesome library! I use it a lot.

After upgrading from v0.17.4 to v0.19.0, sound files with spaces in their names doesn't see to work on iOS anymore. Still works fine on Android though.

**Full Description**
The audio file never seems to start playing on iOS... At least I can't hear it. Worked fine before upgrading to v0.19.0.
The player still reports `PlayerState.PLAYING` though.

After replacing spaces with underscores, everything works fine again.

**Code to Reproduce**
```
AudioCache cache = new AudioCache(prefix: 'assets/sounds/');
AudioPlayer player = await cache.play("My Sound.mp3");
```

**Log Errors**
No error message is logged.

**Platforms**
The bug arises on iOS 14.6.
Still works on Android 6.0.1.

### LINKED ISSUE #1494: feat: better error description for unsupported file formats
### Checklist

- [X] I made sure that the issue I am raising doesn't already exist

### Use case / Problem

Many bug reports describing an error, and the code is not working. But it's not the fault of the library per se.
The file format / codec is just not supported on that platform.

### Proposal / Solution

- Unify the error message for all platforms
- Link to trouble shooting guide: https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md
- Ask questions in the message:
  - Does the platform support this file format?
  - Is the file corrupt or empty?
  - Do you use the correct path, e.g. remove `asset/` for `AssetSource`?
  - Web only: How to handle CORS errors correctly
  - Darwin: test white space in url
- network issue
- a malformed URL
- a missing permission in the app manifest

### Example Code

<details>
<summary>Example Code</summary>

Catch and throw the relevant errors on their native platform.

</details>

### Affected platforms

other

### Platform details

_No response_

### Audio Files/URLs/Sources

_No response_

### Mockups

_No response_

### Related issues / more information

Web:
#1427
#1437
#1327

Darwin:
#1210
#1430
#1473

#748
#972
#1621
#1546

#803 is related, but not yet solved, as it needs a parameter on the native side for the meme type.

### Working on PR

not yet

### LINKED ISSUE #1546: PlatformException(DarwinAudioError, AVPlayerItem.Status.failed on setSourceUrl,
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

\^[[31mAudioPlayers Exception: AudioPlayerException(
	DeviceFileSource(path: /var/mobile/Containers/Data/Application/05BFE1FD-0371-4C27-A279-38645C04E5C3/Library/Caches/recording.aac), 
	PlatformException(DarwinAudioError, AVPlayerItem.Status.failed on setSourceUrl, null, null)<…>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(DarwinAudioError, AVPlayerItem.Status.failed on setSourceUrl, null, null)

### Expected behaviour

  await _player.setSourceDeviceFile(fileUrl);
    _player.play(source);

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

```
  void playAudioWithFile(String fileUrl,
      {Function? onPlaying, Function? onPlayCompleted}) async{
    this.onPlaying = onPlaying;
    this.onPlayCompleted = onPlayCompleted;
    DeviceFileSource source = DeviceFileSource(fileUrl);

    await _player.setSourceDeviceFile(fileUrl);
    _player.play(source);
  }
 ```

### Affected platforms

iOS

### Platform details

Android 正常
ios 报错

### AudioPlayers Version

audioplayers: ^4.1.0

### Build mode

debug

### Audio Files/URLs/Sources

_No response_

### Screenshots

_No response_

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Related issues / more information

_No response_

### Working on PR

no way

### PR DESCRIPTION
**Pull request by Gustl22**
# Description

- feat: Improved error description for unsupported file formats
- fix: Handle white space and special characters in URL and Assets (Web & Darwin)
- test: Test files without file extension (not playable Darwin)

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `refactor:`,
      `docs:`, `chore:`, `test:`, `ci:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation and added dartdoc comments with `///`, where necessary.
- [ ] I have updated/added relevant examples in [example].

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

Closes #1494
Closes #748
Closes #972
Closes #1546

[issue database]: https://github.com/bluefireteam/audioplayers/issues
[Contributor Guide]: https://github.com/bluefireteam/audioplayers/blob/main/contributing.md#feature-requests--prs
[Conventional Commit]: https://conventionalcommits.org
[example]: https://github.com/bluefireteam/audioplayers/tree/main/packages/audioplayers/example

### CODE REVIEW

File: packages/audioplayers/example/integration_test/lib/lib_source_test_data.dart [hunk 1]
```diff
@@ -57,6 +62,16 @@ final invalidAssetTestData = LibSourceTestData(
   duration: null,
 );
 
+final specialCharAssetTestData = LibSourceTestData(
+  source: AssetSource(specialCharAsset),
+  duration: const Duration(milliseconds: 451),
```
Comment (spydon) [inline packages/audioplayers/example/integration_test/lib/lib_source_test_data.dart:67]: What specific duration, how come? 😄

File: troubleshooting.md [hunk 2]
```diff
@@ -94,21 +87,49 @@ There is a required configuration to enable audio do be playing on the backgroun
 
 Or on XCode you can add it as a capability; more details [here](https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/creating_a_basic_video_player_ios_and_tvos/enabling_background_audio).
 
-## Audio Stream Issues
+### [iOS, macOS] Urls or Paths without a file extension
 
-One of the know reasons for streams not playing is that the stream is being gziped by the server, as described [here](https://github.com/bluefireteam/audioplayers/issues/183).
+At the moment player of iOS and macOS (`AVPlayer` on Darwin) only accepts to play files with an extension (like `.mp3` or `.wav`). Make sure these are available or help us fix the issue #803.
```
Comment (spydon) [inline troubleshooting.md:92]:
```suggestion
At the moment, the player of iOS and macOS (`AVPlayer` on Darwin) only accepts to play files with an extension (like `.mp3` or `.wav`). Make sure these are available or help us fix the issue #803.
```

**Review by spydon — APPROVED** [review]

File: packages/audioplayers/example/integration_test/lib/lib_source_test_data.dart (hunk 1 above)
Comment (Gustl22) [reply packages/audioplayers/example/integration_test/lib/lib_source_test_data.dart:67]: I read it out from the `duration` property. It varies a little bit from platform to platform, but not more than 1 or 2 ms. It's only for testing to ensure the same duration is stated for the specific source on each test run.
