### PR TITLE
fix: player state not being updated to completed

### LINKED ISSUE #1242: In audioPlayer.onPlayerComplete event listener, player.state is still playing state
## Checklist
- [x] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [x] I made sure that the issue I am raising doesn't already exist

## Current bug behaviour

When an audio file play finished, audioPlayer.onPlayerComplete is triggered, but in this  event listener, player state is still in playing state.
Also if I have a button, user can click it to get the audio player state, after audio file play finished, user click button, the audio player.state is also in playing state.

## Expected behaviour

In audioPlayer.onPlayerComplete listener, player.state is complete
After audio file play finished, player.state is complete

## Steps to reproduce

1. Add onPlayerComplete listener
2. print player.state in onPlayerComplete listener
3. print output playing

<details>
<summary>
</summary>

```dart
audioPlayer.onPlayerComplete.listen(() {
print(audioPlayer.state==PlayerState.playing);// true
}
<Button onPress()=>{
print(audioPlayer.state==PlayerState.playing);}>click</Button>
// after audio file play finished, button click will output true
```

</details>

## Environment information

* audioplayers version: 1.0.1

Platform: 
* OS name and version: android 10
* Device: android emulator
* build mode: `debug`

* error peculiarities (optional):

### PR DESCRIPTION
**Pull request by itsJoKr**
# Description

This is regression introduced in 1.0.0.

In 0.2.0, this logic was:

```dart
      case 'audio.onComplete':
          player.state = PlayerState.COMPLETED;
          player._completionController.add(null);
```

So along with the completionController stream being update, the state was set to completed. 
In 1.0.0 there is no such functionality:

```dart
      case 'audio.onComplete':
        emitComplete(playerId);
```

Since `audioplayers_platform_interface` package doesn't have a reference to `player.state` anymore because it's now in `audioplayers` package, my fix consisted of simply listening to this same stream in `audioplayers` package and updating the state.

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:`, `chore:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.

I'm not sure how to test this properly.

- [x] I have updated/added relevant documentation and added dartdoc comments with `///`, where necessary.
- [x] I have updated/added relevant examples in [example].

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

Closes #1242

### CODE REVIEW

File: packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart [hunk 1]
```diff
@@ -165,6 +166,7 @@ class MethodChannelAudioplayersPlatform extends AudioplayersPlatform
         emitPosition(playerId, position);
         break;
       case 'audio.onComplete':
+        emitPlayerState(playerId, PlayerState.completed);
```
Comment (itsJoKr) [inline packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart:169]: This is not needed for this particular fix, but I left it for discussion. I was quite confused because other streams from the platform interface are being exposed and available for end-developer.

But PlayerState stream, is created from fresh in the main package (audiplayers.dart) and this stream from platform interface is not used anywhere.

Comment (Gustl22) [reply packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart:169]: Indeed, `emitPlayerState` is not used anywhere. But I would remove it completely from [here](https://github.com/bluefireteam/audioplayers/blob/6fad1cc4443e623e5c94519f130b4004b2dc3857/packages/audioplayers_platform_interface/lib/streams_interface.dart#L52) (maybe in another PR) and call onPlayerState(PlayerState.completed) also in the constructor, when completed event is emitted. @luanpotter what do you think about this? I think `emitPlayerState` is kind of redundant.

**Comment by Gustl22** [comment]
Thank you! I also added a `getState` button in upcoming MR #1238 to test this.

File: packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart (hunk 1 above)
Comment (itsJoKr) [reply packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart:169]: I agree that would make it clearer.

**Comment by itsJoKr** [comment]
I realized I haven't dispose resources properly, so added one more commit.

**Comment by spydon** [comment]
Formatting fails in the CI, if you just run `flutter format .` it should be fine

File: packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart (hunk 1 above)
Comment (Gustl22) [reply packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart:171]: @luanpotter any thoughts?

Comment (luanpotter) [reply packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart:171]: isn't it exposed here?
```
  Stream<ForPlayer<PlayerState>> get playerStateStream =>
      _playerStateStreamController.stream;
```
so are you proposing removing this public accessor?

Comment (Gustl22) [reply packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart:171]: @luanpotter Yes it is exposed, but it never receives any updates / never is called, so basically useless. So the only reason to keep it, would be to propagate, when a stream has started or stopped or released etc. But this is all already done on the dart side, not on the native side.

So currently it does not add any value and is a bit confusing. And I also cannot think of any event, which will be added in the future, which currently cannot be implemented with the other existing events. 

Alternatively we ditch the `emitComplete` in favor of the `emitPlayerState`, but that does not really make sense, if not handling these events on the native side.

Comment (Gustl22) [reply packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart:171]: @luanpotter I think your opinion is quite important here, as it's a breaking change for the interface. Do you agree on my suggestion? Although the removing of `emitPlayerState` does not have to be part of this PR yet. But the implementation to propagate the `onComplete` event on the dart side would be different.

Comment (luanpotter) [reply packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart:171]: I agree. let's remove it. :shipit: 
thanks for the careful explanation :)

File: packages/audioplayers/lib/src/audioplayer.dart [hunk 2]
```diff
@@ -17,6 +17,13 @@ const _uuid = Uuid();
 /// It holds methods to play, loop, pause, stop, seek the audio, and some useful
 /// hooks for handlers and callbacks.
 class AudioPlayer {
+  /// Creates a new instance and assigns an unique id to it.
+  AudioPlayer({String? playerId}) : playerId = playerId ?? _uuid.v4() {
+    _onPlayerCompleteStreamSubscription = onPlayerComplete.listen((_) {
+      state = PlayerState.completed;
+    });
+  }
+
```
Comment (Gustl22) [inline packages/audioplayers/lib/src/audioplayer.dart:26]: I would not change the order of the constructor. I know the it's not the recommended order, but we should change it in one go for the whole packe, if it's really important.
```suggestion
```

File: packages/audioplayers/lib/src/audioplayer.dart [hunk 3]
```diff
@@ -36,6 +43,8 @@ class AudioPlayer {
     _playerState = state;
   }
 
+  StreamSubscription? _onPlayerCompleteStreamSubscription;
```
Comment (Gustl22) [inline packages/audioplayers/lib/src/audioplayer.dart:46]: Can't we declare it with `late`. It should always be available, as it's initialized in the constructor.
```suggestion
  late StreamSubscription _onPlayerCompleteStreamSubscription;
```

File: packages/audioplayers/lib/src/audioplayer.dart [hunk 4]
```diff
@@ -88,9 +97,6 @@ class AudioPlayer {
 
   ReleaseMode get releaseMode => _releaseMode;
 
-  /// Creates a new instance and assigns an unique id to it.
-  AudioPlayer({String? playerId}) : playerId = playerId ?? _uuid.v4();
-
```
Comment (Gustl22) [inline packages/audioplayers/lib/src/audioplayer.dart:93]: Readd constructor here:

```suggestion
  /// Creates a new instance and assigns an unique id to it.
  AudioPlayer({String? playerId}) : playerId = playerId ?? _uuid.v4() {
    _onPlayerCompleteStreamSubscription = onPlayerComplete.listen((_) {
      state = PlayerState.completed;
    });
  }

```

File: packages/audioplayers/lib/src/audioplayer.dart [hunk 5]
```diff
@@ -253,10 +259,13 @@ class AudioPlayer {
...
-    if (!_playerStateController.isClosed) {
-      futures.add(_playerStateController.close());
-    }
+    final futures = <Future>[
+      if (!_playerStateController.isClosed)
+        _playerStateController.close(),
+      if (_onPlayerCompleteStreamSubscription != null)
+        _onPlayerCompleteStreamSubscription!.cancel()
+    ];
+
```
Comment (Gustl22) [inline packages/audioplayers/lib/src/audioplayer.dart:268]: Also no need to check for null, if it's always initialized:

```suggestion
    final futures = <Future>[
      if (!_playerStateController.isClosed) _playerStateController.close(),
      _onPlayerCompleteStreamSubscription.cancel()
    ];

```

File: packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart [hunk 6]
```diff
@@ -5,6 +5,7 @@ import 'dart:typed_data';
 
 import 'package:audioplayers_platform_interface/api/audio_context_config.dart';
 import 'package:audioplayers_platform_interface/api/player_mode.dart';
+import 'package:audioplayers_platform_interface/api/player_state.dart';
```
Comment (Gustl22) [inline packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart:8]: We should remove this again, as player state is already updated in dart implementation. In another MR we can remove all the playerState event stuff from the `audioplayers_interface` as it's not listened and not triggered.

```suggestion
```

File: packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart [hunk 7]
```diff
@@ -167,6 +168,7 @@ class MethodChannelAudioplayersPlatform extends AudioplayersPlatform
         emitPosition(playerId, position);
         break;
       case 'audio.onComplete':
+        emitPlayerState(playerId, PlayerState.completed);
```
Comment (Gustl22) [inline packages/audioplayers_platform_interface/lib/method_channel_audioplayers_platform.dart:171]: Removing, as it's not called or listened to.
```suggestion
```

**Review by Gustl22 — CHANGES_REQUESTED** [review]

File: packages/audioplayers/lib/src/audioplayer.dart (hunk 4 above)
Comment (itsJoKr) [reply packages/audioplayers/lib/src/audioplayer.dart:93]: Sorry, I somehow missed this. I see you are adding commits, so should you add this change too?

Comment (Gustl22) [reply packages/audioplayers/lib/src/audioplayer.dart]: I did all the changes. Hope you agree with them. If not let me know ;D

**Review by Gustl22 — APPROVED** [review]

**Review by spydon — APPROVED** [review]

**Comment by pooblej** [comment]
Hi,  I am using 

audioplayers:
    git:
      url: https://github.com/itsJoKr/audioplayers.git
      path: packages/audioplayers
      ref: f82378f476dcf5a597ef02ba1ed7294eb3a65f7d

from [itsJoKr] fix for this and I can confirm it works for Android - but does not work for iOS or Web
Is there any change the same fix can be applied to resolve these?

--- Sample ---

    play()
    async { await widget.audioPlayer.play(UrlSource(widget.openingAudio_game01[widget.openAudio]));}
    widget.audioPlayer.play(UrlSource(widget.openingAudio_game01[widget.openAudio]));
    widget.audioPlayer.onPlayerComplete.listen((event){
      print(widget.audioPlayer.state == PlayerState.playing);
      if (widget.openAudio < widget.openingAudio_game01.length)
      {       play();        widget.openAudio = widget.openAudio + 1;      }    }    );  }

**Comment by Gustl22** [comment]
@pooblej it should work with latest release also on web. I added tests for it. 
Plz consider opening a separate issue, if still having problems.

**Comment by pooblej** [comment]
@Gustl22 - I amended to use audioplayers:
git:
url: https://github.com/bluefireteam/audioplayers.git

Android continues to work, but iOS and Web don't. 
Is it anything to do with UrlSource?
