### PR TITLE
fix: onPrepared event to wait until player is ready / finished loading the source

### LINKED ISSUE #1118: [v1 rc2] play function on remote freeze UI
The play function may be async, but it still freeze the UI until play start.

### LINKED ISSUE #1359: Audio has a delay after resume to start to play
## Checklist
- [x] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [x] I made sure that the issue I am raising doesn't already exist

Sometimes, when I press to play the audio, it has a big delay to start to play. The `PlayerState` it's `playing` right after press play, the file it's already downloaded.

## Current bug behaviour
1. Set source from deviceFile.
2. `audioPlayer.onPlayerStateChanged` dispatch `isReady` state.
3. Press play button, that calls `audioPlayer.resume()` method.
4. `audioPlayer.onPlayerStateChanged` dispatch `playing` state.
5. Wait until the audio starts to play, sometimes wait more then 1 minute.

## Expected behaviour
1. Set source from deviceFile.
2. `audioPlayer.onPlayerStateChanged` dispatch `isReady` state.
3. Press play button, that calls `audioPlayer.resume()` method.
4. `audioPlayer.onPlayerStateChanged` dispatch `playing` state.
5. Play right after press the button since the state it's ready.

## Reproducing
https://user-images.githubusercontent.com/50436424/209859752-e24fda51-eaee-4547-ab29-0614e38b4229.mp4

## Environment information

* audioplayers version: 1.1.1

Platform 1: Ubuntu 22.10, Ubuntu 22.04 LTS, Ubuntu 18.04 LTS
* build mode: debug and release mode

Platforms tested without any issue:  Windows 10

### LINKED ISSUE #1384: [windows] onDurationChanged return -256204778:48:05.477000 in play local file
image

```
 Flutter (Channel stable, 3.3.10, on Microsoft Windows [版本 10.0.19045.2486], locale zh-CN)
    • Flutter version 3.3.10 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0
```

### PR DESCRIPTION
**Pull request by Gustl22**
# Description

Add a callback when the player has prepared its source, which is tangled to the asynchronous `setSource` method, to improve experience, when player should actually play and not wait for the player to prepare / load the source.

- [ ] Fix: cannot play same source twice on Linux

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:`, `chore:` etc).
- [x] I have read the [Contributor Guide] and followed the process outlined for submitting PRs.
- [x] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation and added dartdoc comments with `///`, where necessary.
- [x] I have updated/added relevant examples in [example].

## Breaking Change

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

## Related Issues

Closes #1118 
Closes #1384 
Closes #1359
#1191

### CODE REVIEW

File: packages/audioplayers/lib/src/audioplayer.dart [hunk 1]
```diff
@@ -120,9 +129,9 @@ class AudioPlayer {
   AudioPlayer({String? playerId}) : playerId = playerId ?? _uuid.v4() {
     _onLogStreamSubscription = onLog.listen(
       (log) => AudioLogger.log('$log\nSource: $_source'),
-      onError: (Object e, [StackTrace? stackTrace]) => AudioLogger.error(
+      onError: (Object e, [StackTrace? st]) => AudioLogger.error(
```
Comment (spydon) [inline packages/audioplayers/lib/src/audioplayer.dart:132]: We are trying to stay away from abbreviations in our code bases

**Review by spydon — APPROVED** [review]

**Review by spydon — APPROVED** [review]

**Comment by spydon** [comment]
Have the tests become flakier recently? 🤔

**Comment by Gustl22** [comment]
Idk what it is, but it's likely not related to this MR. I did a test on the main branch and got similar results. It's just failing without any hint...
https://github.com/bluefireteam/audioplayers/actions/runs/4795110533

I searched everything: Flutter release 3.7.12 only made a fix for Gradle: https://github.com/flutter/flutter/compare/3.7.11...3.7.12
The pubspeck.lock only differs in two packages: `file_picker: 5.2.9` and `synchronized: 3.0.1`.
Probably GH rolled out minor upgrades to their Operating Systems (?): https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230416.1 , but haven't seen anything relevant.

File: packages/audioplayers_platform_interface/lib/src/api/audio_event.dart [hunk 2]
```diff
@@ -33,6 +35,9 @@ class AudioEvent {
   /// Log message in the player scope.
   final String? logMessage;
 
+  /// Weather the
```
Comment (spydon) [inline packages/audioplayers_platform_interface/lib/src/api/audio_event.dart:38]: Missing parts of dartdoc, but it might not be needed, the variable name is quite self explanatory?
(Also Weather 🌤️ -> Whether)

**Review by spydon — APPROVED** [review]

**Review by spydon — APPROVED** [review]

**Comment by Gustl22** [comment]
@spydon do you agree merging it like that. I expect https://github.com/flutter/flutter/issues/126209 to take some time... 😅
